acr = {
  'brb': ['be right back', 'bathroom break'],
  'cc': ['carbon copy', 'i understand'],
  'dl': ['download', 'down low', 'doing laundry'],
  'eta': ['estimated time of arrival', 'edited to add'],
  'gf': ['girlfriend', 'gluten-free'],
  'gg': ['good game', 'good grief'],
  'gl': ['good luck', 'get lost'],
  'hoas': ['hold on a second', 'heck of a shot'],
  'hw': ['homework', 'hardware'],
  'ic': ['i see', 'in character'],
  'im': ['instant messenger', 'instant message'],
  'k': ['ok', 'kiss'],
  'lol': ['laughing out loud', 'league of legends', 'lots of love', 'little old lady'],
  'n/a': ['not available', 'not applicable'],
  'nc': ['no comment', 'nice call', 'not cool'],
  'nm': ['not much', 'nevermind'],
  'np': ['no problem', 'neopets'],
  'ot': ['off topic', 'other topic', 'overtime'],
  'pm': ['pm', 'private message'],
  'pos': ['parent over shoulder', 'piece of shit', 'power of suggestion'],
  're': ['regarding', 'resident evil'],
  'rotfl': ['rolling on the floor laughing', 'rolling over freakin\' laughing'],
  'smh':['shaking my head', 'smash my head', 'scratching my head'],
  'sos': ['someone over shoulder', 'save our souls', 'same old stuff', 'someone special'],
  'tc': ['take care', 'that\'s cool'],
  'ur': ['your', 'you are'],
  'wb': ['write back', 'welcome back', 'way bored'],
  'y': ['why', 'yawning']
}