sigleExpansionAcr = {"2": "To",
"24/7": "Twenty-four hours a day, seven days a week",
"411": "Information",
"AFAIK": "As far as I know",
"AFK": "Away from keyboard",
"AIM": "AOL Instant Messenger",
"AKA": "Also known as",
"AM": "Antemeridian",
"AOL": "America Online",
"ASAP": "As soon as possible",
"ASL": "Age, sex, location",
"ATM": "At the moment",
"B/C": "Because",
"B/W": "Between",
"B4": "Before",
"BBIAB": "Be back in a bit",
"BBL": "Be back later",
"BBS": "Be back soon",
"BCC": "Blind carbon copy",
"BF": "Boyfriend",
"BFF": "Best friends forever",
"BLOG": "Web log",
"BRB": "Be right back",
"BUCK": "Dollar",
"CAB": "Taxi",
"CC": "Carbon copy",
"CYA": "See ya",
"CYE": "Check your email",
"DIY": "Do it yourself",
"DL": "Download",
"ETA": "Edited to add",
"F": "Female",
"FAQ": "Frequently Asked Questions",
"FB": "Facebook",
"FTW": "For the win",
"FUBAR": "Fouled up beyond all recognition",
"FWIW": "For what it's worth",
"FYI": "For your information",
"GF": "Girlfriend",
"GG": "Good grief",
"GJ": "Good job",
"GL": "Good luck",
"GTG": "Got to go",
"HAHA": "Laughing",
"HOAS": "Hold on a second",
"HW": "Homework",
"IC": "I see",
"IIRC": "If I remember correctly",
"IKR": "I know, right?",
"IM": "Instant message",
"IRT": "In regards to",
"J/K": "Just kidding",
"K": "OK",
"L8R": "Later",
"LMAO": "Laughing my a** off",
"LMK": "Let me know",
"LOL": "Laughing out loud",
"MATE": "Friend",
"MMB": "Message me back",
"MMO": "Massively multiplayer online",
"MSG": "Message",
"MYOB": "Mind your own business",
"N/A": "Not Available",
"NC": "Nice call",
"NM": "Not much",
"NP": "No problem",
"OMG": "Oh my gosh",
"OMW": "On my way",
"OT": "Off topic",
"PHAT": "Pretty hot and tempting",
"PK": "Player kill",
"PLS": "Please",
"PM": "Postmeridian",
"POS": "Piece of s***",
"PWN": "To dominate",
"QT": "Cutie",
"RE": "Regarding",
"ROFL": "Rolling over freakin' laughing",
"ROTFL": "Rolling on the floor laughing",
"RPG": "Role-playing game",
"RSVP": "Répondez s'il vous plaît",
"RTFM": "Read the flippin' manual",
"SELFIE": "A picture of yourself",
"SMH": "Shaking my head",
"SOS": "Save our souls",
"SUP": "What's up",
"TBA": "To be announced",
"TBC": "To be continued",
"TBD": "To be determined",
"TC": "Take care",
"THX": "Thanks",
"TIA": "Thanks in advance",
"TLC": "Tender love and care",
"TMI": "Too much information",
"TTFN": "Ta-ta for now",
"TTYL": "Talk to you later",
"TWEET": "Twitter post",
"TXT": "Text",
"TY": "Thank you",
"U": "You",
"U2": "You too",
"UR": "Your",
"W/": "With",
"W/E": "Whatever",
"W/O": "Without",
"W8": "Wait",
"WB": "Write back",
"XDD": "Laughing especially hard",
"XOXO": "Hugs and kisses",
"Y": "Why",
"YW": "You're welcome",
"ZZZ": "Sleeping"
}

#print(sigleExpansionAcr["TC"])